#!/usr/bin/env python3
"""Export a layout from docs/layout.js as an XKB symbols file (Linux/X11/Wayland-xkb).

Usage: python3 tools/export_xkb.py [layout-name=refined]  -> exports/khmer-cluster-<name>.xkb
Only layouts WITHOUT dedicated cluster keys can be exported: XKB maps a key level to a single
Unicode character, so coeng+consonant pair keys would need an IME or a software keyboard.
"""
import sys, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
name = sys.argv[1] if len(sys.argv) > 1 else "refined"
txt = open(os.path.join(ROOT, "docs", "layout.js"), encoding="utf-8").read()
data = json.loads(txt[txt.index("=") + 1: txt.index(";\nwindow.LAYOUT_DEFAULT")])
L = data[name]
if L["info"]["pairs"]:
    sys.exit("layout '%s' has %d pair keys; XKB cannot emit multi-character keys" % (name, len(L["info"]["pairs"])))

XKB = {}
for i, c in enumerate(["KeyQ", "KeyW", "KeyE", "KeyR", "KeyT", "KeyY", "KeyU", "KeyI", "KeyO", "KeyP", "BracketLeft", "BracketRight"]):
    XKB[c] = "AD%02d" % (i + 1)
for i, c in enumerate(["KeyA", "KeyS", "KeyD", "KeyF", "KeyG", "KeyH", "KeyJ", "KeyK", "KeyL", "Semicolon", "Quote"]):
    XKB[c] = "AC%02d" % (i + 1)
for i, c in enumerate(["KeyZ", "KeyX", "KeyC", "KeyV", "KeyB", "KeyN", "KeyM", "Comma", "Period", "Slash"]):
    XKB[c] = "AB%02d" % (i + 1)
for i, c in enumerate(["Digit%d" % d for d in (1, 2, 3, 4, 5, 6, 7, 8, 9, 0)]):
    XKB[c] = "AE%02d" % (i + 1)


def sym(u):
    if not u:
        return "NoSymbol"
    assert len(u) == 1
    if u.isascii():
        return {"1": "1", "2": "2", "3": "3", "4": "4", "5": "5", "6": "6", "7": "7", "8": "8", "9": "9", "0": "0"}[u]
    return "U%04X" % ord(u)


lines = ["// Generated by tools/export_xkb.py from layout '%s' (%s)" % (name, L["info"]["name"]),
         "// Level 1 = base, level 2 = Shift, level 3 = AltGr (Right Alt).",
         'default partial alphanumeric_keys', 'xkb_symbols "basic" {',
         '    name[Group1]= "Khmer (cluster-frequency v2, experimental)";']
for code, k in L["keys"].items():
    lines.append('    key <%s> { type="THREE_LEVEL", [ %s ] };' % (XKB[code], ", ".join(sym(u) for u in k)))
lines += ['    include "level3(ralt_switch)"', "};", ""]
os.makedirs(os.path.join(ROOT, "exports"), exist_ok=True)
out = os.path.join(ROOT, "exports", "khmer-cluster-%s.xkb" % name)
open(out, "w", encoding="utf-8").write("\n".join(lines))
print("wrote", out)
